// src/app/notes/page.tsx
import Link from 'next/link';
import type { Metadata } from 'next';

import { Heading } from '@/components/Heading';
import { Tag } from '@/components/Tag';
import { createSocialMetadata } from '@/lib/metadata';
import { formatDate, getAllNotes } from '@/lib/notes';

const seoTitle = 'Notes – Dennis Yurkevich';
const seoDescription =
  'Browse the latest notes from Dennis Yurkevich covering software engineering, startups, and building products.';

export const metadata: Metadata = {
  title: seoTitle,
  description: seoDescription,
  ...createSocialMetadata({
    title: seoTitle,
    description: seoDescription,
  }),
};

export default function NotesPage() {
  const notes = getAllNotes();

  return (
    <>
      <Heading>Notes</Heading>
      <div className="space-y-4">
        {notes.map((note) => (
          <article key={note.path} className="group">
            <Link href={note.path} className="block space-y-1">
              <div className="flex items-center justify-between gap-4">
                <h2 className="text-xl font-semibold text-foreground transition-colors group-hover:text-primary">
                  {note.title}
                </h2>

                <time
                  dateTime={note.publishedAt}
                  className="whitespace-nowrap text-sm text-muted"
                >
                  {formatDate(note.publishedAt)}
                </time>
              </div>

              <p className="text-sm text-muted-foreground">{note.description}</p>

              <div className="flex flex-wrap gap-2 pt-2">
                {note.tags.map((tag) => (
                  <Tag key={tag} label={tag} />
                ))}
              </div>
            </Link>
          </article>
        ))}
      </div>
    </>
  );
}

// app/pages/notes/index.vue
<script setup lang="ts">
const { data: notes } = await useAsyncData('notes-list', () =>
  queryCollection('notes').order('publishedAt', 'DESC').all()
);

const formatDate = (date: Date) => {
  return new Intl.DateTimeFormat('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  }).format(new Date(date));
};

const seoTitle = 'Notes – Dennis Yurkevich';
const seoDescription =
  'Browse the latest notes from Dennis Yurkevich covering software engineering, startups, and building products.';
useSeoMeta({
  title: seoTitle,
  ogTitle: seoTitle,
  description: seoDescription,
  ogDescription: seoDescription,
  twitterCard: 'summary_large_image',
});
</script>

<template>
  <Heading>Notes</Heading>
  <div class="space-y-4">
    <article v-for="note in notes" :key="note.path" class="group">
      <NuxtLink :to="note.path" class="space-y-1">
        <div class="flex items-center justify-between gap-4">
          <h2
            class="text-xl font-semibold text-foreground transition-colors group-hover:text-primary"
          >
            {{ note.title }}
          </h2>

          <time
            :datetime="new Date(note.publishedAt).toISOString()"
            class="text-sm text-muted whitespace-nowrap"
          >
            {{ formatDate(new Date(note.publishedAt)) }}
          </time>
        </div>

        <p class="text-muted-foreground text-sm">
          {{ note.description }}
        </p>

        <div class="flex flex-wrap gap-2 pt-2">
          <Tag v-for="tag in note.tags" :key="tag" :label="tag" />
        </div>
      </NuxtLink>
    </article>
  </div>
</template>
